// ui/src/components/views/agentChatView/AgentChatHistory.tsx
import React, { useState, useRef, useEffect, useCallback } from "react";
import { Bubble } from "@ant-design/x";
import XMarkdown from "@ant-design/x-markdown";
import {
  ToolOutlined,
  CheckCircleOutlined,
  RobotOutlined,
  DownOutlined,
  RightOutlined,
} from "@ant-design/icons";
import type { ChatMessageVO, SseMessageType, ToolCall, ToolResponse } from "../../../types";

interface AgentChatHistoryProps {
  messages: ChatMessageVO[];
  displayAgentStatus?: boolean;
  agentStatusText?: string;
  agentStatusType?: SseMessageType;
}

// 工具调用展示组件（简化版，用于 assistant 消息内）
const ToolCallDisplay: React.FC<{ toolCall: ToolCall }> = ({ toolCall }) => {
  let parsedArgs: Record<string, unknown> = {};
  try {
    parsedArgs = JSON.parse(toolCall.arguments) as Record<string, unknown>;
  } catch {
    // 如果解析失败，使用原始字符串
  }

  const argCount = Object.keys(parsedArgs).length;
  const argPreview = argCount > 0 
    ? Object.keys(parsedArgs).slice(0, 2).join(", ") + (argCount > 2 ? "..." : "")
    : toolCall.arguments.slice(0, 50) + (toolCall.arguments.length > 50 ? "..." : "");

  return (
    <div className="text-xs text-gray-500 flex items-center gap-1.5">
      <ToolOutlined className="text-blue-500" />
      <span className="font-mono text-blue-600">{toolCall.name}</span>
      {argPreview && (
        <>
          <span className="text-gray-400">·</span>
          <span className="text-gray-500 truncate max-w-[200px]">{argPreview}</span>
        </>
      )}
    </div>
  );
};

// 工具响应展示组件（可折叠）
const ToolResponseDisplay: React.FC<{ toolResponse: ToolResponse }> = ({
  toolResponse,
}) => {
  const [expanded, setExpanded] = useState(false);
  
  let parsedData: unknown = null;
  let isJson = false;
  let dataPreview = "";
  
  try {
    parsedData = JSON.parse(toolResponse.responseData);
    isJson = true;
    const jsonStr = JSON.stringify(parsedData);
    dataPreview = jsonStr.length > 100 ? jsonStr.slice(0, 100) + "..." : jsonStr;
  } catch {
    dataPreview = toolResponse.responseData.length > 100 
      ? toolResponse.responseData.slice(0, 100) + "..." 
      : toolResponse.responseData;
  }

  return (
    <div className="my-1.5 text-xs">
      <div 
        className="flex items-center gap-2 text-gray-500 cursor-pointer hover:text-gray-700 transition-colors"
        onClick={() => setExpanded(!expanded)}
      >
        {expanded ? (
          <DownOutlined className="text-gray-400" />
        ) : (
          <RightOutlined className="text-gray-400" />
        )}
        <CheckCircleOutlined className="text-green-500" />
        <span className="font-mono text-green-600">{toolResponse.name}</span>
        <span className="text-gray-400">·</span>
        <span className="text-gray-500 truncate flex-1">{dataPreview}</span>
      </div>
      {expanded && (
        <div className="ml-5 mt-1.5 p-2 bg-gray-50 rounded border border-gray-200">
          <div className="text-xs text-gray-600 font-mono">
            {isJson ? (
              <pre className="whitespace-pre-wrap break-words overflow-x-auto max-h-60 overflow-y-auto">
                {JSON.stringify(parsedData, null, 2)}
              </pre>
            ) : (
              <div className="whitespace-pre-wrap break-words">
                {toolResponse.responseData}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

const AgentChatHistory: React.FC<AgentChatHistoryProps> = ({
  messages,
  displayAgentStatus = false,
  agentStatusText = "",
  agentStatusType,
}) => {
  // 滚动容器引用
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  // 是否允许自动滚动（用户是否接近底部）
  const [isNearBottom, setIsNearBottom] = useState(true);
  // 容错阈值（像素）
  const SCROLL_THRESHOLD = 20;
  // 上一次消息数量，用于检测新消息
  const prevMessagesLengthRef = useRef(messages.length);

  // 检查是否接近底部
  const checkIfNearBottom = useCallback(() => {
    const container = scrollContainerRef.current;
    if (!container) return false;

    const { scrollTop, clientHeight, scrollHeight } = container;
    const distanceFromBottom = scrollHeight - scrollTop - clientHeight;
    return distanceFromBottom <= SCROLL_THRESHOLD;
  }, []);

  // 滚动到底部
  const scrollToBottom = useCallback(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    // 使用 requestAnimationFrame 确保 DOM 更新完成后再滚动
    requestAnimationFrame(() => {
      if (container) {
        container.scrollTop = container.scrollHeight;
      }
    });
  }, []);

  // 处理滚动事件，实时更新是否接近底部的状态
  const handleScroll = useCallback(() => {
    const nearBottom = checkIfNearBottom();
    setIsNearBottom(nearBottom);
  }, [checkIfNearBottom]);

  // 监听滚动事件
  useEffect(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    // 初始化时检查是否在底部（延迟执行以避免同步 setState）
    const initTimer = setTimeout(() => {
      setIsNearBottom(checkIfNearBottom());
    }, 0);

    container.addEventListener("scroll", handleScroll, { passive: true });

    return () => {
      clearTimeout(initTimer);
      container.removeEventListener("scroll", handleScroll);
    };
  }, [handleScroll, checkIfNearBottom]);

  // 监听消息变化，决定是否自动滚动
  useEffect(() => {
    const hasNewMessage = messages.length > prevMessagesLengthRef.current;
    prevMessagesLengthRef.current = messages.length;

    // 如果有新消息且用户接近底部，则自动滚动
    if (hasNewMessage && isNearBottom) {
      scrollToBottom();
    }
  }, [messages, isNearBottom, scrollToBottom]);

  // 当 displayAgentStatus 变化时，如果用户接近底部，也自动滚动
  useEffect(() => {
    if (displayAgentStatus && isNearBottom) {
      scrollToBottom();
    }
  }, [displayAgentStatus, isNearBottom, scrollToBottom]);

  // 获取状态标签
  const getStatusLabel = () => {
    switch (agentStatusType) {
      case "AI_PLANNING":
        return "规划中";
      case "AI_THINKING":
        return "思考中";
      case "AI_EXECUTING":
        return "执行中";
      default:
        return "处理中";
    }
  };

  return (
    <div 
      ref={scrollContainerRef}
      className="flex-1 px-6 md:px-16 pt-6 overflow-y-scroll"
    >
      {messages.map((message) => {
        return (
          <div className="mb-4" key={message.id}>
            {/* Assistant 消息 */}
            {message.role === "assistant" && (
              <Bubble
                content={
                  <div className="w-full">
                    {/* 工具调用展示 */}
                    {message.metadata?.toolCalls &&
                      message.metadata.toolCalls.length > 0 && (
                        <div className="mb-2 flex flex-wrap gap-2">
                          {message.metadata.toolCalls.map((toolCall) => (
                            <ToolCallDisplay key={toolCall.id} toolCall={toolCall} />
                          ))}
                        </div>
                      )}
                    {/* 消息内容 */}
                    {message.content && (
                      <div>
                        <XMarkdown
                          streaming={{ enableAnimation: false, hasNextChunk: true }}
                        >
                          {message.content}
                        </XMarkdown>
                      </div>
                    )}
                  </div>
                }
                placement="start"
              />
            )}

            {/* Tool 消息 - 简洁展示，不使用气泡 */}
            {message.role === "tool" && message.metadata?.toolResponse && (
              <div className="flex justify-start">
                <div className="max-w-[85%]">
                  <ToolResponseDisplay toolResponse={message.metadata.toolResponse} />
                </div>
              </div>
            )}

            {/* User 消息 */}
            {message.role === "user" && (
              <Bubble content={message.content} placement="end" />
            )}

            {/* System 消息 */}
            {message.role === "system" && (
              <div className="flex justify-center">
                <div className="px-3 py-1 bg-gray-100 text-gray-600 text-xs rounded-full flex items-center gap-1">
                  <RobotOutlined />
                  <span>{message.content}</span>
                </div>
              </div>
            )}
          </div>
        );
      })}
      {displayAgentStatus && (
        <div className="mb-3">
          <div
            className="animate-pulse"
            style={{
              animation: "pulse 0.8s cubic-bezier(0.4, 0, 0.6, 1) infinite",
              filter: "brightness(1.15)",
            }}
          >
            <Bubble
              content={
                <span className="flex items-center gap-2">
                  <span
                    className="font-semibold text-blue-600"
                    style={{
                      animation:
                        "pulse 0.7s cubic-bezier(0.4, 0, 0.6, 1) infinite",
                      textShadow:
                        "0 0 10px rgba(37, 99, 235, 1), 0 0 20px rgba(37, 99, 235, 0.8), 0 0 30px rgba(37, 99, 235, 0.5)",
                      filter: "brightness(1.3)",
                    }}
                  >
                    ✨ {getStatusLabel()}
                  </span>
                  <span className="text-gray-400">·</span>
                  <span className="text-gray-600">{agentStatusText}</span>
                </span>
              }
              placement="start"
            />
          </div>
        </div>
      )}
    </div>
  );
};

export default AgentChatHistory;

// ui/src/components/views/agentChatView/AgentChatHistory.vue
<template>
  <div ref="scrollContainerRef" class="flex-1 px-6 md:px-16 pt-6 overflow-y-auto">
    <div v-for="message in messages" :key="message.id" class="mb-4">
      <!-- Assistant 消息 -->
      <template v-if="message.role === 'assistant'">
        <div class="flex justify-start">
          <div class="max-w-[85%]">
            <!-- 工具调用展示 -->
            <div v-if="message.metadata?.toolCalls?.length" class="mb-2 flex flex-wrap gap-2">
              <div
                v-for="tc in message.metadata.toolCalls"
                :key="tc.id"
                class="text-xs text-gray-500 dark:text-[#8ba4c0] flex items-center gap-1.5"
              >
                <ToolOutlined class="text-blue-500" />
                <span class="font-mono text-blue-600 dark:text-[#00e5ff]">{{ tc.name }}</span>
                <span v-if="tc.arguments" class="text-gray-400">·</span>
                <span class="text-gray-500 dark:text-[#5a7090] truncate max-w-[200px]">{{ formatArgs(tc.arguments) }}</span>
              </div>
            </div>
            <!-- 消息内容 Markdown -->
            <div v-if="message.content" class="prose prose-sm dark:prose-invert max-w-none bubble-card">
              <div v-html="renderMarkdown(message.content)" />
            </div>
          </div>
        </div>
      </template>

      <!-- Tool 消息 -->
      <template v-else-if="message.role === 'tool' && message.metadata?.toolResponse">
        <div class="flex justify-start">
          <div class="max-w-[85%]">
            <ToolResponseCard :tool-response="message.metadata.toolResponse" />
          </div>
        </div>
      </template>

      <!-- User 消息 -->
      <template v-else-if="message.role === 'user'">
        <div class="flex justify-end">
          <div class="max-w-[80%] px-4 py-2.5 rounded-2xl rounded-br-md bg-blue-500 text-white text-sm">
            {{ message.content }}
          </div>
        </div>
      </template>

      <!-- System 消息 -->
      <template v-else-if="message.role === 'system'">
        <div class="flex justify-center">
          <div class="px-3 py-1 bg-gray-100 dark:bg-[#0e1422] text-gray-600 dark:text-[#8ba4c0] text-xs rounded-full flex items-center gap-1">
            <RobotOutlined />
            <span>{{ message.content }}</span>
          </div>
        </div>
      </template>
    </div>

    <!-- Agent 状态显示 -->
    <div v-if="displayAgentStatus" class="mb-3 animate-pulse">
      <div class="flex justify-start">
        <div class="max-w-[85%] px-4 py-2.5 rounded-2xl rounded-bl-md bg-gray-100 dark:bg-[#0e1422] border border-gray-200 dark:border-[rgba(0,229,255,0.15)]">
          <span class="text-sm text-gray-600 dark:text-[#8ba4c0] flex items-center gap-2">
            <span class="font-semibold text-blue-600 dark:text-[#00e5ff]">✨ {{ getStatusLabel() }}</span>
            <span class="text-gray-400">·</span>
            <span>{{ agentStatusText }}</span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick, onMounted, onUnmounted } from "vue";
import { RobotOutlined, ToolOutlined } from "@ant-design/icons-vue";
import { marked } from "marked";
import ToolResponseCard from "./ToolResponseCard.vue";
import type { ChatMessageVO, SseMessageType } from "../../../types";

const props = defineProps<{
  messages: ChatMessageVO[];
  displayAgentStatus?: boolean;
  agentStatusText?: string;
  agentStatusType?: SseMessageType;
}>();

const scrollContainerRef = ref<HTMLDivElement | null>(null);
const isNearBottom = ref(true);
const prevMessagesLength = ref(0);
const SCROLL_THRESHOLD = 20;

function renderMarkdown(content: string): string {
  return marked.parse(content) as string;
}

function formatArgs(args: string): string {
  try {
    const parsed = JSON.parse(args);
    const keys = Object.keys(parsed);
    if (keys.length === 0) return args.slice(0, 50);
    return keys.slice(0, 2).join(", ") + (keys.length > 2 ? "..." : "");
  } catch {
    return args.slice(0, 50) + (args.length > 50 ? "..." : "");
  }
}

function checkIfNearBottom(): boolean {
  const container = scrollContainerRef.value;
  if (!container) return false;
  const { scrollTop, clientHeight, scrollHeight } = container;
  return scrollHeight - scrollTop - clientHeight <= SCROLL_THRESHOLD;
}

function scrollToBottom() {
  requestAnimationFrame(() => {
    if (scrollContainerRef.value) {
      scrollContainerRef.value.scrollTop = scrollContainerRef.value.scrollHeight;
    }
  });
}

function handleScroll() {
  isNearBottom.value = checkIfNearBottom();
}

onMounted(() => {
  const container = scrollContainerRef.value;
  if (!container) return;
  container.addEventListener("scroll", handleScroll, { passive: true });
  setTimeout(() => { isNearBottom.value = checkIfNearBottom(); }, 0);
});

onUnmounted(() => {
  scrollContainerRef.value?.removeEventListener("scroll", handleScroll);
});

watch(() => props.messages.length, (newLen) => {
  const hasNew = newLen > prevMessagesLength.value;
  prevMessagesLength.value = newLen;
  if (hasNew && isNearBottom.value) {
    nextTick(() => scrollToBottom());
  }
});

watch(() => props.displayAgentStatus, (val) => {
  if (val && isNearBottom.value) {
    nextTick(() => scrollToBottom());
  }
});

function getStatusLabel() {
  switch (props.agentStatusType) {
    case "AI_PLANNING": return "规划中";
    case "AI_THINKING": return "思考中";
    case "AI_EXECUTING": return "执行中";
    default: return "处理中";
  }
}
</script>
