// ui/src/components/views/AgentChatView.tsx
import React, { useCallback, useEffect, useState } from "react";
import { useParams, useNavigate, useLocation } from "react-router-dom";
import { message as antdMessage } from "antd";
import AgentChatHistory from "./agentChatView/AgentChatHistory.tsx";
import AgentChatInput from "./agentChatView/AgentChatInput.tsx";
import {
  createChatMessage,
  createChatSession,
  getChatMessagesBySessionId,
  getChatSession,
} from "../../api/api.ts";
import { BASE_URL } from "../../api/http.ts";
import { useAgents } from "../../hooks/useAgents.ts";
import { useChatSessions } from "../../hooks/useChatSessions.ts";
import EmptyAgentChatView from "./agentChatView/EmptyAgentChatView.tsx";
import type { ChatMessageVO, SseMessage, SseMessageType } from "../../types";

const AgentChatView: React.FC = () => {
  const { chatSessionId } = useParams<{ chatSessionId: string }>();
  const navigate = useNavigate();
  const { state } = useLocation();
  const [loading, setLoading] = useState(false);
  const { agents } = useAgents();
  const { refreshChatSessions } = useChatSessions();

  const [messages, setMessages] = useState<ChatMessageVO[]>([]);

  const addMessage = (message: ChatMessageVO) => {
    setMessages((prevMessages) => [...prevMessages, message]);
  };

  const [agentId, setAgentId] = useState<string>("");

  const getChatMessages = useCallback(async () => {
    if (!chatSessionId) {
      return;
    }
    const resp = await getChatMessagesBySessionId(chatSessionId);
    setMessages(resp.chatMessages);

    const fetchData = async () => {
      const resp = await getChatSession(chatSessionId);
      // setChatSession(resp.chatSession);
      setAgentId(resp.chatSession.agentId);
    };
    fetchData().then();
  }, [chatSessionId]);

  useEffect(() => {
    if (!chatSessionId) {
      return;
    }
    getChatMessages().then();
  }, [chatSessionId, getChatMessages]);

  const handleSendMessage = async (value: string | { text: string }) => {
    // 处理 Sender 组件可能传递的不同格式
    const message = typeof value === "string" ? value : value.text;

    console.log(message);

    if (!message || !message.trim()) return;

    // 如果没有 chatSessionId，创建新会话
    if (!chatSessionId) {
      if (!agentId) {
        antdMessage.warning("请先创建一个智能体助手");
        return;
      }
      setLoading(true);
      try {
        const response = await createChatSession({
          agentId: agentId,
          title: message.slice(0, 20),
        });
        // 刷新聊天会话列表
        await refreshChatSessions();
        // 导航到新创建的会话
        navigate(`/chat/${response.chatSessionId}`, {
          replace: true,
          // 携带初始化消息
          state: {
            init: false,
            initMessage: message,
          },
        });
      } catch (error) {
        console.error("创建聊天会话失败:", error);
        antdMessage.error("创建聊天会话失败，请重试");
      } finally {
        setLoading(false);
      }
    } else {
      if (state?.init) {
        console.log("init", state.initMessage);
        await createChatMessage({
          agentId: agentId ?? "",
          sessionId: chatSessionId,
          role: "user",
          content: state.initMessage ?? "",
        });
      } else {
        console.log("ask", message);
        await createChatMessage({
          agentId: agentId ?? "",
          sessionId: chatSessionId,
          role: "user",
          content: message,
        });
      }
      await getChatMessages();
    }
  };

  const [displayAgentStatus, setDisplayAgentStatus] = useState<boolean>(false);
  const [agentStatusText, setAgentStatusText] = useState("");
  const [agentStatusType, setAgentStatusType] = useState<
    SseMessageType | undefined
  >(undefined);

  useEffect(() => {
    // sse 连接处理, 不是对话消息不开连接
    if (!chatSessionId) {
      return;
    }
    const sseBaseUrl = BASE_URL.replace(/\/api$/, '');
    const es = new EventSource(
      `${sseBaseUrl}/sse/connect/${chatSessionId}`,
    );
    es.onmessage = (event) => {
      console.log("Received message:", event.data);
    };
    es.onerror = (error) => {
      console.error("SSE error:", error);
    };

    es.addEventListener("message", (event) => {
      // 解析 JSON
      const message = JSON.parse(event.data) as SseMessage;
      if (message.type === "AI_GENERATED_CONTENT") {
        // 将 AI 生成的内容存到 messages 中
        addMessage(message.payload.message);
      } else if (message.type === "AI_PLANNING") {
        setDisplayAgentStatus(true);
        setAgentStatusText(message.payload.statusText);
        setAgentStatusType("AI_PLANNING");
      } else if (message.type === "AI_THINKING") {
        setDisplayAgentStatus(true);
        setAgentStatusText(message.payload.statusText);
        setAgentStatusType("AI_THINKING");
      } else if (message.type === "AI_EXECUTING") {
        setDisplayAgentStatus(true);
        setAgentStatusText(message.payload.statusText);
        setAgentStatusType("AI_EXECUTING");
      } else if (message.type === "AI_DONE") {
        setDisplayAgentStatus(false);
        setAgentStatusText("");
        setAgentStatusType(undefined);
      } else {
        throw new Error(`Unknown message type: ${message.type}`);
      }
    });

    es.addEventListener("init", (event) => {
      console.log("Received init message:", event.data);
    });

    return () => {
      console.log("Closing SSE connection.");
      es.close();
    };
  }, [chatSessionId]);

  // 如果没有 chatSessionId，显示提示界面
  if (!chatSessionId) {
    return (
      <EmptyAgentChatView
        agents={agents}
        loading={loading}
        handleSendMessage={handleSendMessage}
      />
    );
  }

  // 如果有 chatSessionId，显示正常的聊天界面
  return (
    <div className="flex flex-col h-full">
      <AgentChatHistory
        messages={messages}
        displayAgentStatus={displayAgentStatus}
        agentStatusText={agentStatusText}
        agentStatusType={agentStatusType}
      />
      <div className="border-t border-gray-200 p-4 bg-white">
        <AgentChatInput onSend={handleSendMessage} />
      </div>
    </div>
  );
};

export default AgentChatView;

// ui/src/components/views/AgentChatView.vue
<template>
  <!-- 无 chatSessionId 时显示提示界面 -->
  <EmptyAgentChatView
    v-if="!chatSessionId"
    :agents="agents"
    :loading="loading"
  />

  <!-- 有 chatSessionId 时显示正常聊天界面 -->
  <div v-else class="flex flex-col h-full">
    <AgentChatHistory
      :messages="messages"
      :display-agent-status="displayAgentStatus"
      :agent-status-text="agentStatusText"
      :agent-status-type="agentStatusType"
    />
    <AgentChatInput @send="handleSendMessage" />
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted } from "vue";
import { useRoute, useRouter } from "vue-router";
import { message } from "ant-design-vue";
import AgentChatHistory from "./agentChatView/AgentChatHistory.vue";
import AgentChatInput from "./agentChatView/AgentChatInput.vue";
import EmptyAgentChatView from "./agentChatView/EmptyAgentChatView.vue";
import { createChatMessage, createChatSession, getChatMessagesBySessionId, getChatSession } from "../../api/api";
import { BASE_URL } from "../../api/http";
import { useAgents } from "../../composables/useAgents";
import { useChatSessions } from "../../composables/useChatSessions";
import type { ChatMessageVO, SseMessage, SseMessageType } from "../../types";

const route = useRoute();
const router = useRouter();
const { agents } = useAgents();
const { refreshChatSessions } = useChatSessions();

const loading = ref(false);
const messages = ref<ChatMessageVO[]>([]);
const agentId = ref("");

const displayAgentStatus = ref(false);
const agentStatusText = ref("");
const agentStatusType = ref<SseMessageType | undefined>(undefined);

const chatSessionId = ref<string | undefined>(undefined);

// 监听路由参数变化
watch(
  () => route.params.chatSessionId,
  (newId) => {
    chatSessionId.value = newId as string | undefined;
  },
  { immediate: true }
);

function addMessage(message: ChatMessageVO) {
  messages.value = [...messages.value, message];
}

async function fetchMessages() {
  if (!chatSessionId.value) return;
  const resp = await getChatMessagesBySessionId(chatSessionId.value);
  messages.value = resp.chatMessages;
  const sessionResp = await getChatSession(chatSessionId.value);
  agentId.value = sessionResp.chatSession.agentId;
}

watch(chatSessionId, (newId) => {
  if (newId) fetchMessages();
});

async function handleSendMessage(data: { text: string }) {
  const text = data.text;
  if (!text || !text.trim()) return;

  if (!chatSessionId.value) {
    if (!agentId.value) {
      // 取第一个 agent
      if (agents.value.length > 0) {
        agentId.value = agents.value[0].id;
      } else {
        message.warning("请先创建一个智能体助手");
        return;
      }
    }
    loading.value = true;
    try {
      const resp = await createChatSession({ agentId: agentId.value, title: text.slice(0, 20) });
      await refreshChatSessions();
      router.replace(`/chat/${resp.chatSessionId}`);
    } catch {
      message.error("创建聊天会话失败，请重试");
    } finally {
      loading.value = false;
    }
  } else {
    await createChatMessage({
      agentId: agentId.value ?? "",
      sessionId: chatSessionId.value,
      role: "user",
      content: text,
    });
    await fetchMessages();
  }
}

// SSE 连接
let es: EventSource | null = null;

watch(chatSessionId, (newId, oldId) => {
  if (oldId && es) {
    es.close();
    es = null;
  }
  if (!newId) return;

  const sseBaseUrl = BASE_URL.replace(/\/api$/, "");
  es = new EventSource(`${sseBaseUrl}/sse/connect/${newId}`);

  es.addEventListener("message", (event) => {
    const msg = JSON.parse(event.data) as SseMessage;
    if (msg.type === "AI_GENERATED_CONTENT") {
      addMessage(msg.payload.message);
    } else if (msg.type === "AI_PLANNING") {
      displayAgentStatus.value = true;
      agentStatusText.value = msg.payload.statusText;
      agentStatusType.value = "AI_PLANNING";
    } else if (msg.type === "AI_THINKING") {
      displayAgentStatus.value = true;
      agentStatusText.value = msg.payload.statusText;
      agentStatusType.value = "AI_THINKING";
    } else if (msg.type === "AI_EXECUTING") {
      displayAgentStatus.value = true;
      agentStatusText.value = msg.payload.statusText;
      agentStatusType.value = "AI_EXECUTING";
    } else if (msg.type === "AI_DONE") {
      displayAgentStatus.value = false;
      agentStatusText.value = "";
      agentStatusType.value = undefined;
    }
  });

  es.onerror = (error) => {
    console.error("SSE error:", error);
  };
});

onUnmounted(() => {
  if (es) {
    es.close();
  }
});
</script>
